CONFIG_ZMK_KEYBOARD_NAME="Quacken Zero"
CONFIG_ZMK_POINTING=y
CONFIG_ZMK_BATTERY_REPORTING=y
CONFIG_ZMK_BATTERY_REPORT_INTERVAL=300
## Uncomment the following line if the name is incorrect
# CONFIG_ZMK_SETTINGS_RESET_ON_START=y
